# Site settings
baseURL = "https://extabay.github.io/website/"
languageCode = "es-ES"
title = 'Jardín Extabay'
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "RSS", "sitemap"]
disableHugoGeneratorInject = true

# Local preview mode
relativeURLs = true
uglyURLs = true

# Copyright
copyright = "&copy;2025 Jardín Extabay"

# Required to publish in GitHub Pages
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[services]
  [services.googleAnalytics]
    # Enter your tracking code to enable Google Analytics
    ID = ""

[params]

  # Metadata for search engines and social sharing
  author = "Jardín Extabay"
  description = "Reuniones y celebraciones en un entorno único."
  shareImage = "images/extabay-logo.png"
  twitterHandle = ""

  # Whether you purchased the license from the author.
  licensed = false

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/extabay-logo.png"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #

  [[params.links]]
    [params.links.list3]
      heading = "Servicios"

      [[params.links.list3.link]]
        text = "Reuniones"
        url = "es/servicios/reuniones.html"

      [[params.links.list3.link]]
        text = "Celebraciones"
        url = "es/servicios/celebraciones.html"

      [[params.links.list3.link]]
        text = "Otros"
        url = "es/servicios/otros.html"

  [[params.links]]
    [params.links.list2]
      heading = "Social"

      [[params.links.list2.link]]
        text = "Facebook"
        url = "https://www.facebook.com/profile.php?id=61579638446112"
        new_tab = true # new tab

      [[params.links.list2.link]]
        text = "Instagram"
        url = "https://www.instagram.com/jardinextabay/"
        new_tab = true # new tab

      [[params.links.list2.link]]
        text = "TikTok"
        url = "https://www.tiktok.com/@jardinextabay"
        new_tab = true # new tab

  [[params.links]]
    [params.links.list1]
      heading = "Contacto"

      [[params.links.list1.link]]
        text = "jardinextabay@gmail.com"
        url = "email:jardinextabay@gmail.com"
        new_tab = false # Default, open at same tab

      [[params.links.list1.link]]
        text = "+52 (1) 333 123456"
        url = "tel:+35635777488"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split

[server]
[[server.headers]]
    for = '/**'
    [server.headers.values]
      Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' https://dummyimage.com"
      Referrer-Policy = 'strict-origin-when-cross-origin'
      X-Content-Type-Options = 'nosniff'
      X-Frame-Options = 'DENY'
      X-XSS-Protection = '1; mode=block'
